title: Bruzu: Dynamically generate Images with URL string
email: support@htmlcsstoimage.com
description: >- # this means to ignore newlines until "baseurl:"
  A very simple yet powerful image generation API. The Bruzu Image API returns an image in response to a URL GET request.
baseurl: ""
url: "https://docs.bruzu.com"
remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/bruzu-logo.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  
  
  # Aux links for the upper right navigation


# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


plugins:
  - jekyll-sitemap
  - jekyll-octicons
  - jekyll-last-modified-at


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/bruzu/docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree"

footer_content: "Bruzu.com <br> &copy; 2021 Bruzu.<style> .site-footer{ display:none; } </style>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Aux links for the upper right navigation
aux_links:
  "Get an API Key":
    - "https://bruzu.com"
  "Demo":
    - "https://bruzu.com"
